version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: local_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  n8n:
    image: n8nio/n8n:latest
    container_name: local_n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - redis

  waha:
    image: devlikeapro/waha:latest
    container_name: local_waha
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - waha_sessions:/app/.sessions
      - waha_media:/app/.media
    depends_on:
      - n8n

volumes:
  redis_data:
  n8n_data:
  waha_sessions:
  waha_media: